### PR TITLE
Handle get cookies with oauth (ex: Google)

### PR DESCRIPTION
**Pull request by louisthomaspro**
Hi, your lib is very useful!

I tried to implement it but look like it doesn't work with cookies using oauth.
As the session cookie is too big for cookies, supabase slipt the value into 2 cookies:
image
`sb-etbfmqkktewuqbpktqvf-auth-token.0` and  `sb-etbfmqkktewuqbpktqvf-auth-token.1`

I updated the `getAuthTokensFromCookies()` method to handle those those type of cookies.

---

Moreover, I needed to change `subaseServerClient` and `supabaseServerAuth` into functions as I am facing this error:
```
Error: `cookies` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
``` 

Fix:
```ts
// Export the initialized Supabase client and AuthManager
export const supabaseServerClient = () => createSupabaseServerClient()
export const supabaseServerAuth = () => new AuthManager(supabaseServerClient(), process.env.SUPABASE_JWT_SECRET!)
```

Regards,
---

### CODE REVIEW

**Comment by Zanzofily** [comment]
Thank you @louisthomaspro. The package currently doesn't support cookie chunking you are correct.

It seems like your solution is fine, but it would stop the application from working if the cookie isn't chunked and too short. Consider using a different regex, something like `sb-[a-z]+-auth-token(\.\d+)?$` maybe?

The other error you are encountering might be happening because you are calling this file on the client. Do you have "server-only" at the top of the file you are using `createSupabaseServerClient` on?

**Comment by Zanzofily** [comment]
How is this going @louisthomaspro, some people raised this issue on the supabase-auth, would be helpful to get this merged.

**Comment by louisthomaspro** [comment]
The solution I gave `const cookieNameRegex = /^sb-[a-z]+-auth-token.*$/` works for both, chunked an unchunked cookies.
I tried your solution, but it is not working on my side for chunked cookies.

For the cookies error, even with or without "server-only", I am facing the same issue.

**Comment by Zanzofily** [comment]
@louisthomaspro just gave your regex a go, you are correct. it works for both!

I will update readme to include your example as well since it's going to be more stable.

**Pull request merged**
